"""Small deterministic JSON Schema to Python/TypeScript/fixture generator."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator  # type: ignore[import-untyped]


@dataclass(frozen=True)
class GeneratedContracts:
    python_path: Path
    typescript_path: Path
    fixture_path: Path


def _identifier(value: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", value)
    result = "".join(word[:1].upper() + word[1:] for word in words) or "SkillPayload"
    return result if not result[0].isdigit() else f"Skill{result}"


def _python_type(schema: dict[str, Any]) -> str:
    value = schema.get("type")
    nullable = isinstance(value, list) and "null" in value
    raw_base = (
        next((item for item in value if item != "null"), "object")
        if isinstance(value, list)
        else value
    )
    base = raw_base if isinstance(raw_base, str) else "object"
    result = {"string": "str", "integer": "int", "number": "float", "boolean": "bool"}.get(
        base,
        "dict[str, object]"
        if base == "object"
        else "list[object]"
        if base == "array"
        else "object",
    )
    return f"{result} | None" if nullable else result


def _typescript_type(schema: dict[str, Any]) -> str:
    value = schema.get("type")
    values = (
        [item for item in value if isinstance(item, str)]
        if isinstance(value, list)
        else [value if isinstance(value, str) else "object"]
    )
    mapped = {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "object": "Record<string, unknown>",
        "array": "unknown[]",
        "null": "null",
    }
    return " | ".join(dict.fromkeys(mapped.get(item, "unknown") for item in values))


def _example(schema: dict[str, Any]) -> Any:
    if "default" in schema:
        return schema["default"]
    if "examples" in schema and schema["examples"]:
        return schema["examples"][0]
    if "enum" in schema and schema["enum"]:
        return schema["enum"][0]
    kind = schema.get("type")
    if isinstance(kind, list):
        kind = next((item for item in kind if item != "null"), "null")
    if kind == "object":
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        return {
            key: _example(value)
            for key, value in sorted(properties.items())
            if key in required and isinstance(value, dict)
        }
    fallback: dict[str, Any] = {
        "array": [],
        "string": "example",
        "integer": 1,
        "number": 1.0,
        "boolean": False,
    }
    return fallback.get(kind) if isinstance(kind, str) else None


def generate_contracts(
    schema_path: str | Path, destination: str | Path, *, name: str
) -> GeneratedContracts:
    schema_file = Path(schema_path).resolve()
    schema = json.loads(schema_file.read_text(encoding="utf-8"))
    Draft202012Validator.check_schema(schema)
    if schema.get("type") != "object":
        raise ValueError("top-level Skill schemas must be objects")
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    model_name = _identifier(name)
    python_fields = [
        f"    {key}: {_python_type(value)}" + ("" if key in required else " = None")
        for key, value in sorted(properties.items())
    ]
    python_text = (
        "# Generated by vav skill schema generate; do not edit.\n"
        "from pydantic import BaseModel, ConfigDict\n\n\n"
        f"class {model_name}(BaseModel):\n"
        '    model_config = ConfigDict(extra="forbid", frozen=True)\n'
        + ("\n".join(python_fields) if python_fields else "    pass")
        + "\n"
    )
    ts_fields = [
        f"  readonly {key}{'' if key in required else '?'}: {_typescript_type(value)};"
        for key, value in sorted(properties.items())
    ]
    ts_text = (
        "// Generated by vav skill schema generate; do not edit.\n"
        f"export interface {model_name} {{\n" + "\n".join(ts_fields) + "\n}\n"
    )
    root = Path(destination).resolve()
    root.mkdir(parents=True, exist_ok=True)
    python_path = root / f"{name}.py"
    typescript_path = root / f"{name}.ts"
    fixture_path = root / f"{name}.fixture.json"
    python_path.write_text(python_text, encoding="utf-8")
    typescript_path.write_text(ts_text, encoding="utf-8")
    fixture_path.write_text(
        json.dumps(_example(schema), indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return GeneratedContracts(python_path, typescript_path, fixture_path)
