<script setup lang="ts">
import { localizeAdminLabel, localizeAdminValue } from "../display";

export type AdminColumn = { key: string; label: string; priority?: "primary" | "secondary"; sensitive?: boolean };
defineProps<{ caption: string; columns: AdminColumn[]; rows: Array<Record<string, unknown>>; rowKey: string; selected?: string[]; loading?: boolean }>();
defineEmits<{ select: [keys: string[]] }>();
</script>
<template><div class="v-admin-table" :aria-busy="loading || undefined"><table><caption>{{ caption }}</caption><thead><tr><th v-if="selected" scope="col"><span class="sr-only">选择</span></th><th v-for="column in columns" :key="column.key" scope="col" :data-priority="column.priority ?? 'secondary'">{{ localizeAdminLabel(column.key, column.label) }}</th></tr></thead><tbody><tr v-for="row in rows" :key="String(row[rowKey])"><td v-if="selected"><input type="checkbox" :aria-label="`选择 ${String(row[rowKey])}`" :checked="selected.includes(String(row[rowKey]))" @change="$emit('select', selected.includes(String(row[rowKey])) ? selected.filter((key) => key !== String(row[rowKey])) : [...selected, String(row[rowKey])])" /></td><td v-for="column in columns" :key="column.key" :data-label="localizeAdminLabel(column.key, column.label)" :data-priority="column.priority ?? 'secondary'">{{ column.sensitive ? '••••' : localizeAdminValue(row[column.key], column.key) }}</td></tr></tbody></table><p v-if="!rows.length">当前无数据。请调整筛选条件或检查数据源。</p></div></template>
<style scoped>table{width:100%;border-collapse:collapse}caption{text-align:left;font-weight:700;padding-block:var(--vav-space-3)}th,td{text-align:left;padding:var(--vav-space-3);border-bottom:1px solid var(--vav-color-border)}input{min-width:var(--vav-component-touch-target-minimum);min-height:var(--vav-component-touch-target-minimum)}.sr-only{position:absolute;clip-path:inset(50%)}@media(max-width:48rem){thead{position:absolute;clip-path:inset(50%)}tr{display:grid;margin-bottom:var(--vav-space-3);padding:var(--vav-space-3);border:1px solid var(--vav-color-border);border-radius:var(--vav-radius-sm)}td{display:grid;grid-template-columns:minmax(7rem,40%) 1fr;gap:var(--vav-space-2)}td::before{content:attr(data-label);font-weight:700}td[data-priority="secondary"]{color:var(--vav-color-text-muted)}}</style>
