export const ADMIN_TIME_ZONE = "Asia/Shanghai";
export const ADMIN_TIME_ZONE_LABEL = "UTC+8";

const fieldLabels: Record<string, string> = {
  id: "编号",
  code: "代码",
  name: "名称",
  title: "标题",
  description: "说明",
  status: "状态",
  state: "状态",
  type: "类型",
  kind: "类别",
  locale: "语言",
  provider: "服务商",
  channel: "渠道",
  source: "来源",
  visibility: "可见性",
  created_at: "创建时间（UTC+8）",
  createdAt: "创建时间（UTC+8）",
  updated_at: "更新时间（UTC+8）",
  updatedAt: "更新时间（UTC+8）",
  published_at: "发布时间（UTC+8）",
  starts_at: "开始时间（UTC+8）",
  ends_at: "结束时间（UTC+8）",
  valid_from: "生效时间（UTC+8）",
  valid_until: "失效时间（UTC+8）",
  expires_at: "过期时间（UTC+8）",
  occurred_at: "发生时间（UTC+8）",
  requested_at: "申请时间（UTC+8）",
  resolved_at: "处理时间（UTC+8）",
  last_exposed_at: "最近曝光时间（UTC+8）",
  started_at: "开始时间（UTC+8）",
  scheduled_starts_at: "计划开始时间（UTC+8）",
  trigger_at: "触发时间（UTC+8）",
  promotion_offer_expires_at: "邀请到期时间（UTC+8）",
  product_code: "商品编码",
  product_type: "商品类型",
  fulfillment_type: "履约方式",
  internal_name: "内部名称",
  default_locale: "默认语言",
  category_id: "分类编号",
  sku_count: "SKU 数量",
  purchasable_from: "可售开始时间（UTC+8）",
  purchasable_until: "可售截止时间（UTC+8）",
  featured: "精选",
  sort_order: "排序权重",
  version: "版本",
  current_stage_code: "当前阶段",
  record_state: "记录状态",
  identifier: "标识",
  decision: "判定",
  severity: "严重程度",
  event_type: "事件类型",
  actor_type: "操作者类型",
  actor_user_id: "操作者用户编号",
  actor_session_id: "操作者会话编号",
  target_type: "操作对象类型",
  target_id: "操作对象编号",
  request_id: "请求编号",
  reason: "操作原因",
  metadata: "附加信息",
  event_metadata: "附加信息",
  before_state: "变更前状态",
  after_state: "变更后状态",
  ip_address_hash: "IP 地址哈希",
  user_agent_hash: "浏览器标识哈希",
  subject_type: "对象类型",
  request_type: "申请类型",
  attempt_count: "尝试次数",
  translation_status: "翻译状态",

  // Written out rather than composed: Chinese reorders around English
  // prepositions (by / to / of / for / after / when) and needs an explicit
  // measure word for units, so left-to-right token concatenation produces
  // phrases like "允许档案使用由AI" or "可编辑窗口小时".
  accessibility_description: "无障碍说明",
  action_suggestions: "操作建议",
  allow_edit_after_submit: "允许提交后编辑",
  allow_ip_suggestion: "允许按 IP 推断归属地",
  allow_profile_facts: "允许使用档案事实",
  allow_profile_use_by_ai: "允许 AI 使用档案",
  allow_service_history: "允许使用服务历史",
  allow_service_history_use_by_ai: "允许 AI 使用服务历史",
  allow_unknown: "允许未知项",
  assigned_to: "指派给",
  assigned_to_user_id: "受理人用户编号",
  authorized_by: "授权人",
  bodies: "正文",
  budget_currency: "预算币种",
  budget_limit_minor: "预算上限（最小货币单位）",
  contract_checksums: "契约校验和",
  daily_received_limit: "每日接收上限",
  date_of_birth: "出生日期",
  deep_link_template: "深链模板",
  delete_existing_when_disabled: "停用时删除既有记录",
  description_blocks: "说明段落",
  destination: "目标地址",
  edit_window_hours: "可编辑窗口（小时）",
  estimated_duration_minutes: "预计时长（分钟）",
  exploration_level: "探索程度",
  extended_recommendations_enabled: "启用扩展推荐",
  feature_manifest: "功能清单",
  fixture_manifest: "夹具清单",
  follow_up_type: "跟进类型",
  followed_user_registered: "被关注用户已注册",
  freeze_note: "冻结备注",
  hoped_for_relationship: "期望的关系",
  immediate_danger_possible: "可能存在即时危险",
  is_active: "是否启用",
  is_met: "是否满足",
  is_primary: "是否主要",
  is_public: "是否公开",
  is_required: "是否必填",
  last_four: "卡号后四位",
  max_offers: "最大推荐数",
  max_quantity_per_user: "每人最大数量",
  occurred_on: "发生日期",
  ordinary_advice_allowed: "允许一般性建议",
  payment_timing_override: "支付时点覆盖",
  payment_timing_policy: "支付时点策略",
  per_subject: "按对象计",
  per_user_redemption_limit: "每人核销上限",
  post_event_choice_enabled: "启用活动后互选",
  preferred_locale: "偏好语言",
  privacy_consent_version: "隐私同意版本",
  privacy_disclosure: "隐私告知",
  privacy_mode: "隐私模式",
  privacy_request_id: "隐私请求编号",
  privacy_version: "隐私版本",
  purchase_limit_per_user: "每人购买上限",
  rate_limit_per_minute: "每分钟速率上限",
  rating: "评分",
  rating_value: "评分值",
  recommendations_paused: "推荐已暂停",
  required_watch_basis_points: "要求观看比例（基点）",
  sample: "样本",
  searchable_by_platform_users: "平台用户可搜索",
  seo_description: "SEO 描述",
  short_description: "简短说明",
  skill_name: "技能名称",
  social_description: "社交分享描述",
  source_locator: "来源定位",
  sufficient_for_response: "足以生成回复",
  terms_version: "条款版本",
  to_plan_code: "目标方案代码",
  to_stage_code: "目标阶段代码",
  ai_processing_consent_id: "AI 处理同意编号",
  allow_contact_exchange_after_mutual_confirmation: "允许双向确认后交换联系方式",
  artifact_checksum_sha256: "产物校验和（SHA256）",
  backup_reference_encrypted: "备份引用（已加密）",
  compare_at_amount_minor: "划线价（最小货币单位）",
  confidence_basis_points: "置信度（基点）",
  contingency_plan: "应急预案",
  emergency_guidance_required: "需要紧急指引",
  evidence_checksum_sha256: "证据校验和（SHA256）",
  feedback_personalization_enabled: "启用反馈个性化",
  human_referral_required: "需要人工转介",
  long_term_memory_enabled: "启用长期记忆",
  manual_intervention_supported: "支持人工介入",
  minimum_score_basis_points: "最低得分（基点）",
  no_selection_reason_code: "未选择原因代码",
  no_selection_reason_note: "未选择原因备注",
  passing_score_basis_points: "及格分（基点）",
  post_event_choice_closes_at: "活动后互选截止时间（UTC+8）",
  post_event_choice_opens_at: "活动后互选开放时间（UTC+8）",
  quiet_hours_enabled: "启用免打扰时段",
  robots: "搜索引擎抓取规则",
  rollout_basis_points: "灰度比例（基点）",
  step_up_authenticated_at: "二次认证时间（UTC+8）",
  advice_disclaimer_code: "建议免责声明代码",
  advice_encrypted: "建议内容（已加密）",
  advice_generated_at: "建议生成时间（UTC+8）",
  advice_model: "建议生成模型",
  advice_prompt_version: "建议提示词版本",
  advice_status: "建议状态",
  cancel_at_period_end: "到期时取消",
  cancel_reason: "取消原因",
  cover_is_fallback: "封面为兜底图",
  input_cost_per_1k_millicents: "输入成本（每千 token，毫分）",
  input_cost_per_million_minor: "输入成本（每百万 token，最小货币单位）",
  output_cost_per_1k_millicents: "输出成本（每千 token，毫分）",
  output_cost_per_million_minor: "输出成本（每百万 token，最小货币单位）",
  privacy_accepted_at: "隐私条款接受时间（UTC+8）",
  privacy_consented_at: "隐私同意时间（UTC+8）",
  rate_limit_per_second: "每秒速率上限",
  replaced_by_certificate_id: "替换为证书编号",
  replaced_by_session_id: "替换为会话编号",
  require_all_required_exercises: "要求完成全部必修练习",
  require_all_required_lessons: "要求完成全部必修课时",
  required_exercise_pass_basis_points: "练习及格线（基点）",
  scheduled_for: "计划时间（UTC+8）",
  summarized_through_turn: "已总结至轮次",
  superseded_by_snapshot_id: "被取代为快照编号",
  terms_accepted_at: "条款接受时间（UTC+8）",
  to_generation: "目标代次",
  to_state: "目标状态",
  to_status: "目标状态",
  user_a_id: "用户 A 编号",
  user_b_id: "用户 B 编号",
  allowed_agent_profiles: "允许的智能体档案",
  visible_in_activity_directory: "在活动目录可见",
  visible_in_matchmaking: "在红娘场景可见",
  allow_public_quote: "允许公开引用",
  allowed_uses: "允许用途",
  max_selections: "最多选择数",
  min_notice_minutes: "最短提前通知（分钟）",
  min_selections: "最少选择数",
  prohibited_uses: "禁止用途",
  quiet_hours_end: "免打扰时段结束",
  quiet_hours_start: "免打扰时段开始",
  quiet_hours_timezone: "免打扰时段时区",
  ttl_hours: "存活时长（小时）",
};

const tokenLabels: Record<string, string> = {
  id: "编号", code: "代码", name: "名称", title: "标题", status: "状态", state: "状态",
  type: "类型", kind: "类别", record: "记录", current: "当前", stage: "阶段", source: "来源",
  target: "目标", subject: "对象", event: "事件", request: "申请", response: "响应", reason: "原因",
  actor: "操作者", session: "会话", metadata: "附加信息", before: "变更前", after: "变更后",
  address: "地址", hash: "哈希", agent: "智能体", action: "操作", role: "角色", rbac: "角色权限",
  created: "创建", updated: "更新", published: "发布", requested: "申请", resolved: "处理", occurred: "发生",
  start: "开始", starts: "开始", end: "结束", ends: "结束", valid: "有效", from: "起始", until: "截止",
  expires: "过期", last: "最近", time: "时间", date: "日期", at: "时间", count: "数量", total: "总计",
  active: "启用", enabled: "启用", disabled: "停用", pending: "待处理", approved: "已批准",
  rejected: "已拒绝", completed: "已完成", failed: "失败", draft: "草稿", archived: "已归档",
  public: "公开", private: "私密", internal: "内部", missing: "缺失", verified: "已验证",
  production: "生产", certified: "已认证", not: "未", course: "课程", activity: "活动", counseling: "咨询",
  membership: "会员", digital: "数字", service: "服务", access: "访问", bundle: "组合", package: "套餐",
  subscription: "订阅", ticket: "票务", admission: "准入", appointment: "预约",
  credits: "次数", credit: "次数", entitlement: "权益", ai: "AI", email: "邮件", sms: "短信",
  push: "推送", in: "站内", app: "应用", system: "系统", manual: "手动", automatic: "自动",
  percentage: "百分比", fixed: "固定", amount: "金额", once: "一次性", recurring: "周期性",
  monthly: "每月", yearly: "每年", daily: "每日", weekly: "每周", visible: "可见", hidden: "隐藏",
  low: "低", medium: "中", high: "高", critical: "严重", open: "待处理", closed: "已关闭",
  recorded: "已记录", success: "成功", succeeded: "成功", warning: "警告", info: "信息", blocked: "已阻断", ready: "就绪",
  user: "用户", admin: "管理员", profile: "档案", policy: "策略", rule: "规则", template: "模板",
  delivery: "投递", provider: "服务商", locale: "语言", channel: "渠道", visibility: "可见性",
  default: "默认", language: "语言", product: "商品", fulfillment: "履约", category: "分类",
  price: "价格", inventory: "库存", promotion: "优惠", campaign: "活动", notification: "通知",
  processing: "处理", translation: "翻译", anonymous: "匿名", member: "成员", members: "成员",
  decision: "判定", severity: "严重程度", primary: "主要", metric: "指标", signal: "信号",
  sku: "SKU", scheduled: "计划", trigger: "触发", offer: "邀请", exposed: "曝光", purchasable: "可售",
  auth: "身份认证", login: "登录", registration: "注册", account: "账户", password: "密码", reset: "重置",
  refresh: "刷新", token: "令牌", reuse: "重复使用", detected: "已检测", family: "系列", revoked: "已撤销",
  removed: "已移除", locked: "已锁定", verification: "验证", sent: "已发送", bypassed: "已绕过",
  invitation: "邀请", accepted: "已接受", restored: "已恢复", suspended: "已暂停", assigned: "已分配",
  content: "内容", entry: "条目", submit: "提交", review: "审核", version: "版本",
  changed: "已变更", media: "媒体", deleted: "已删除", navigation: "导航",
  site: "网站", setting: "设置", contact: "联系", submission: "提交记录",
  yes: "是", no: "否", true: "是", false: "否", zh: "中文", en: "英文",

  // Batch 2026-08: the dictionary only covered a fraction of the API
  // surface, so most admin columns rendered as 字段（raw_name）. These cover
  // every field name reachable from the backend response schemas.
  // Unit tokens carry their own parentheses because concatenation has no
  // connectives: "编辑窗口（小时）" reads, "编辑窗口小时" does not.
  "1": "1",
  "2": "2",
  absent: "缺席",
  accept: "接受",
  acceptance: "验收",
  accessibility: "无障碍",
  acknowledged: "已确认",
  acknowledgement: "确认",
  activate: "启用",
  adjustment: "调整",
  advance: "提前",
  affected: "受影响",
  age: "年龄",
  aggregate: "聚合",
  aggregation: "聚合",
  algorithm: "算法",
  allocation: "分配",
  allow: "允许",
  allowed: "允许",
  alt: "替代",
  and: "与",
  anonymity: "匿名度",
  answer: "答案",
  answers: "答案",
  appeal: "申诉",
  applicable: "适用",
  application: "应用",
  approval: "审批",
  arguments: "参数",
  artifact: "产物",
  assessment: "评估",
  asset: "素材",
  assignee: "受理人",
  assisted: "辅助",
  attempted: "已尝试",
  attempts: "尝试",
  audience: "受众",
  audit: "审计",
  author: "作者",
  authoritative: "权威",
  authorization: "授权",
  authorized: "授权",
  auto: "自动",
  backfill: "回填",
  backup: "备份",
  base: "基础",
  base64: "Base64",
  basis: "依据",
  batch: "批次",
  behavior: "行为",
  benefit: "权益",
  benefits: "权益",
  bidirectional: "双向",
  billing: "账单",
  bio: "简介",
  biography: "自述",
  birth: "出生",
  blind: "盲区",
  block: "阻断",
  blocks: "段落",
  body: "正文",
  book: "价目表",
  booking: "预约",
  boolean: "布尔",
  brief: "简要",
  buffer: "缓冲",
  build: "构建",
  business: "业务",
  bypass: "绕过",
  byte: "字节",
  cadence: "节奏",
  calls: "调用",
  cancellation: "取消",
  candidate: "候选",
  candidates: "候选",
  canonical: "规范",
  capabilities: "能力",
  capability: "能力",
  capacity: "容量",
  caption: "说明文字",
  card: "卡片",
  cart: "购物车",
  catalog: "目录",
  categories: "分类",
  causation: "因果",
  certainty: "确定度",
  change: "变更",
  changes: "变更",
  channels: "渠道",
  check: "检查",
  checked: "签到",
  checkin: "签到",
  checkpoint: "检查点",
  checks: "检查",
  checksum: "校验和",
  checksums: "校验和",
  child: "子",
  choice: "选项",
  chosen: "选中",
  citation: "引用",
  citations: "引用",
  city: "城市",
  claim: "主张",
  claims: "主张",
  clarifying: "澄清",
  classification: "分类",
  client: "客户端",
  closes: "关闭",
  closure: "收尾",
  codes: "代码",
  cold: "冷",
  collection: "收集",
  columns: "列",
  command: "命令",
  comment: "备注",
  commit: "提交",
  compare: "对比",
  comparisons: "对比",
  compatible: "兼容",
  compensation: "补偿",
  completeness: "完整度",
  completion: "完成",
  compliance: "合规",
  condition: "条件",
  conditions: "条件",
  confidence: "置信度",
  config: "配置",
  configuration: "配置",
  confirmation: "确认",
  confirmed: "已确认",
  consent: "同意",
  consented: "已同意",
  consents: "同意",
  constraint: "约束",
  consumer: "消费方",
  context: "上下文",
  contingency: "应急",
  control: "控制",
  conversation: "会话",
  converts: "转换",
  cooldown: "冷却",
  correlation: "关联",
  counterpart: "对方",
  country: "国家",
  coupon: "优惠券",
  cover: "封面",
  credential: "凭据",
  criteria: "标准",
  criterion: "评分项",
  criticality: "关键程度",
  cross: "跨",
  currency: "币种",
  cursor: "游标",
  custom: "自定义",
  customer: "客户",
  cutoff: "截止",
  danger: "危险",
  data: "数据",
  database: "数据库",
  dataset: "数据集",
  days: "（天）",
  deadline: "截止",
  deduplication: "去重",
  definition: "定义",
  delete: "删除",
  delta: "增量",
  desired: "期望",
  details: "明细",
  device: "设备",
  difference: "差异",
  difficulty: "难度",
  digests: "摘要",
  dimension: "维度",
  directory: "目录",
  disclaimer: "免责声明",
  disclosure: "告知",
  discriminator: "判别",
  display: "展示",
  distinct: "去重",
  diversification: "多样性",
  document: "文档",
  documentation: "文档",
  domain: "业务域",
  drill: "演练",
  dry: "试",
  due: "到期",
  duration: "时长",
  early: "提前",
  effect: "效果",
  eligibility: "准入",
  emergency: "紧急",
  emotional: "情绪",
  empathy: "共情",
  encrypted: "（已加密）",
  enforcement: "强制",
  entity: "实体",
  envelope: "信封",
  environment: "环境",
  error: "错误",
  escalation: "升级",
  evaluated: "已评估",
  evidence: "证据",
  exception: "异常",
  excerpt: "摘要",
  exchange: "交换",
  exclude: "排除",
  execution: "执行",
  exercise: "练习",
  existing: "既有",
  expected: "预期",
  experiment: "实验",
  explanation: "说明",
  exposure: "曝光",
  external: "外部",
  failure: "失败",
  faith: "信仰",
  fallback: "兜底",
  feedback: "反馈",
  field: "字段",
  fields: "字段",
  file: "文件",
  filename: "文件名",
  filters: "筛选",
  final: "最终",
  findings: "发现",
  fingerprint: "指纹",
  flag: "开关",
  flow: "流程",
  follow: "跟进",
  form: "表单",
  format: "形式",
  free: "免费",
  frequency: "频率",
  functional: "功能",
  gap: "差距",
  gate: "关卡",
  gender: "性别",
  generated: "生成",
  geography: "地区",
  git: "Git",
  grace: "宽限",
  grading: "评分",
  grant: "授予",
  granted: "已授予",
  group: "群组",
  growth: "成长",
  guardrail: "护栏",
  guidance: "指引",
  handoff: "交接",
  hard: "硬",
  headline: "标题",
  help: "帮助",
  hold: "占位",
  holder: "持有人",
  hoped: "期望",
  hours: "（小时）",
  html: "HTML",
  human: "人工",
  hypothesis: "假设",
  idempotency: "幂等",
  identifier: "标识",
  ids: "编号",
  image: "图片",
  immediate: "立即",
  import: "导入",
  importance: "重要度",
  index: "索引",
  indicators: "指标",
  infrastructure: "基础设施",
  input: "输入",
  instructor: "讲师",
  intake: "受理",
  intent: "意图",
  interests: "兴趣",
  interval: "周期",
  intervention: "人工介入",
  intro: "简介",
  introduced: "引入",
  introduction: "自我介绍",
  invitee: "受邀人",
  invocation: "调用",
  ip: "IP",
  issued: "签发",
  item: "条目",
  items: "条目",
  job: "作业",
  join: "加入",
  journey: "历程",
  justification: "理由",
  k: "K",
  key: "键",
  keys: "键",
  kinds: "类别",
  knowledge: "知识",
  label: "文案",
  languages: "语言",
  late: "迟到",
  leakage: "泄露",
  learning: "学习",
  legal: "法务",
  lesson: "课时",
  level: "等级",
  license: "许可",
  licensor: "授权方",
  lifecycle: "生命周期",
  lifestyle: "生活方式",
  likelihood: "可能性",
  limit: "上限",
  line: "行",
  lineage: "血缘",
  link: "链接",
  linked: "关联",
  load: "负载",
  local: "本地",
  localization: "本地化",
  localizations: "本地化",
  localized: "本地化",
  location: "地点",
  lock: "锁",
  long: "长",
  lookup: "查找",
  manifest: "清单",
  mapping: "映射",
  mark: "标记",
  marriage: "婚姻",
  match: "匹配",
  matchmaking: "红娘",
  max: "最大",
  maximum: "最大",
  mbti: "MBTI",
  memory: "记忆",
  mentor: "导师",
  message: "消息",
  messages: "消息",
  method: "方法",
  metrics: "指标",
  milestone: "里程碑",
  millicents: "（毫分）",
  mime: "MIME",
  min: "最小",
  minimum: "最小",
  minor: "（最小货币单位）",
  minutes: "（分钟）",
  mitigation: "缓解",
  mode: "模式",
  model: "模型",
  modified: "修改",
  module: "模块",
  modules: "模块",
  ms: "（毫秒）",
  mutual: "双向",
  namespace: "命名空间",
  new: "新",
  next: "下一",
  node: "节点",
  nodes: "节点",
  non: "非",
  note: "备注",
  notes: "备注",
  notice: "须知",
  notify: "通知",
  number: "编号",
  offset: "偏移",
  offsets: "偏移",
  og: "OG",
  online: "在线",
  only: "仅",
  opening: "开场",
  opens: "开放",
  operation: "操作",
  operator: "操作员",
  opportunity: "机会",
  opt: "选择",
  opted: "已选择",
  options: "选项",
  order: "订单",
  outcome: "结果",
  outcomes: "成果",
  output: "输出",
  override: "覆盖",
  oversell: "超售",
  overselling: "超售",
  oversized: "超大",
  owner: "负责人",
  owning: "归属",
  page: "页",
  parameters: "参数",
  parent: "父",
  participant: "参与者",
  participants: "参与者",
  participation: "参与",
  passing: "及格",
  path: "路径",
  pattern: "模式",
  payload: "载荷",
  payment: "支付",
  pem: "PEM",
  period: "周期",
  permission: "权限",
  permissions: "权限",
  personalization: "个性化",
  phone: "电话",
  photo: "照片",
  photos: "照片",
  place: "地点",
  placeholder: "占位",
  plain: "纯",
  plan: "方案",
  planned: "计划",
  platform: "平台",
  playback: "播放",
  played: "已播放",
  point: "方式",
  points: "基点",
  position: "位置",
  postal: "邮政",
  precision: "精度",
  prefix: "前缀",
  prerequisite: "前置",
  prerequisites: "前置条件",
  preview: "预览",
  pricing: "定价",
  priority: "优先级",
  process: "流程",
  processed: "已处理",
  producer: "生产方",
  profiles: "档案",
  prohibited: "禁止",
  prompt: "提示词",
  proposal: "提案",
  provenance: "来源溯源",
  publish: "发布",
  publisher: "发布方",
  purchase: "购买",
  purpose: "用途",
  purposes: "用途",
  quality: "质量",
  quantity: "数量",
  query: "查询",
  question: "题目",
  questions: "问题",
  quiet: "免打扰",
  quota: "配额",
  quote: "报价",
  quoted: "报价",
  rag: "RAG",
  ranking: "排名",
  rate: "速率",
  rationale: "理由",
  read: "读取",
  reading: "阅读",
  reasons: "原因",
  receipt: "回执",
  recent: "最近",
  recipient: "接收方",
  recommendation: "推荐",
  recommendations: "推荐",
  reconciliation: "对账",
  records: "记录",
  redemption: "核销",
  ref: "引用",
  reference: "引用",
  references: "引用",
  referral: "转介",
  reflection: "反思",
  reflections: "反思",
  refs: "引用",
  refund: "退款",
  regenerate: "重新生成",
  region: "地区",
  regions: "地区",
  relationship: "关系",
  relaxable: "可放宽",
  relaxation: "放宽",
  release: "发布",
  reminder: "提醒",
  repair: "修复",
  report: "报告",
  reported: "已上报",
  required: "必填",
  requirement: "需求",
  requirements: "需求",
  requires: "需要",
  reservation: "预约",
  residual: "残余",
  resolution: "处置",
  resource: "资源",
  resources: "资源",
  responses: "响应",
  restoration: "恢复",
  restriction: "限制",
  result: "结果",
  results: "结果",
  retrieval: "检索",
  retry: "重试",
  reveal: "公布",
  reverse: "反向",
  reviewed: "已审核",
  revision: "修订",
  rights: "权利",
  risk: "风险",
  roles: "角色",
  rollout: "灰度",
  route: "路由",
  rows: "行",
  rules: "规则",
  run: "运行",
  runbook: "处置手册",
  safe: "安全",
  safety: "安全",
  sales: "销售",
  salt: "盐值",
  sbom: "SBOM",
  scale: "量表",
  scenario: "场景",
  schema: "结构",
  scope: "范围",
  score: "得分",
  scored: "计分",
  scoring: "评分",
  searchable: "可搜索",
  seat: "座位",
  seats: "席位",
  secondary: "次要",
  seconds: "（秒）",
  sections: "板块",
  seed: "种子",
  segment: "客群",
  segments: "客群",
  selected: "已选",
  selection: "选择",
  selections: "选择",
  self: "自我",
  semantic: "语义",
  sensitivity: "敏感度",
  seo: "SEO",
  sequence: "序号",
  settings: "设置",
  sha256: "SHA256",
  shadow: "影子",
  share: "分享",
  shared: "共享",
  short: "短",
  show: "展示",
  signals: "信号",
  signature: "签名",
  single: "单次",
  size: "大小",
  skip: "跳过",
  slot: "时段",
  slug: "别名",
  snapshot: "快照",
  social: "社交",
  socialization: "社交",
  sort: "排序",
  space: "空间",
  specialty: "擅长",
  spot: "点",
  stable: "稳定",
  stackability: "叠加规则",
  started: "开始",
  statement: "陈述",
  step: "步骤",
  stock: "库存",
  strategy: "策略",
  strengths: "优势",
  subtitle: "副标题",
  subtotal: "小计",
  sufficient: "充分",
  summary: "摘要",
  supersede: "取代",
  supersedes: "取代",
  support: "支持",
  supported: "支持",
  supporting: "支持",
  surface: "展位",
  survey: "问卷",
  synthetic: "合成",
  tab: "标签页",
  targeting: "定向",
  task: "任务",
  tax: "税",
  team: "团队",
  term: "期",
  tested: "测试",
  text: "文本",
  thresholds: "阈值",
  timezone: "时区",
  tokens: "令牌数",
  tool: "工具",
  top: "前",
  topic: "主题",
  topics: "主题",
  training: "训练",
  treatment: "处置",
  trial: "试用",
  ttl: "存活",
  turn: "轮次",
  types: "类型",
  uncertainty: "不确定",
  understanding: "理解",
  unit: "单位",
  units: "单位",
  unresolved: "未解决",
  url: "链接",
  use: "使用",
  used: "使用",
  users: "用户",
  uses: "使用",
  value: "值",
  values: "值",
  variable: "变量",
  variables: "变量",
  venue: "场地",
  versions: "版本",
  video: "视频",
  vision: "愿景",
  visited: "已访问",
  waitlist: "候补",
  warnings: "警告",
  website: "网站",
  weekday: "星期",
  weight: "权重",
  window: "窗口",
  write: "写入",
  post: "活动后",
  up: "升级",
  robots: "搜索引擎抓取",
  "1k": "每千",
  accessed: "访问",
  activated: "启用",
  actual: "实际",
  added: "添加",
  answered: "回答",
  assignment: "分配",
  assistant: "助手",
  attempt: "尝试",
  attendance: "出勤",
  authored: "撰写",
  avatar: "头像",
  back: "回滚",
  balance: "余额",
  baseline: "基线",
  bound: "绑定",
  boundary: "边界",
  bps: "（基点）",
  bucket: "存储桶",
  calculation: "计算",
  calling: "调用",
  cancelled: "已取消",
  captions: "字幕",
  case: "个案",
  certificate: "证书",
  character: "字符",
  chooser: "选择方",
  chunk: "分块",
  circuit: "熔断",
  concepts: "概念",
  connector: "连接器",
  consecutive: "连续",
  considered: "参与评估",
  consumed: "已消耗",
  converted: "已转化",
  cost: "成本",
  couple: "伴侣",
  curriculum: "课程大纲",
  dating: "交友",
  decided: "已决定",
  declared: "申报",
  decline: "拒绝",
  dedupe: "去重",
  deletion: "删除",
  delivered: "投递",
  deployed: "部署",
  detail: "详情",
  dimensions: "尺寸",
  discount: "折扣",
  discrepancy: "差异",
  dismissed: "忽略",
  dispatched: "派发",
  distance: "距离",
  drm: "数字版权",
  edit: "编辑",
  editable: "可编辑",
  edited: "编辑",
  effective: "生效",
  eligible: "符合条件",
  embedding: "向量",
  ended: "结束",
  enrolled: "报名",
  enrollment: "报名",
  entered: "进入",
  errors: "错误",
  estimate: "预估",
  evaluation: "评估",
  excluded: "排除",
  exclusion: "排除",
  exercises: "练习",
  exit: "退出",
  exited: "退出",
  expired: "过期",
  exponent: "指数",
  facilitator: "引导者",
  failures: "失败",
  finished: "完成",
  first: "首次",
  fixture: "夹具",
  fixtures: "夹具",
  followed: "关注",
  followee: "被关注者",
  follower: "关注者",
  forbidden: "禁止",
  formatted: "格式化",
  fragment: "片段",
  frozen: "冻结",
  fulfilled: "履约",
  generation: "代次",
  geocode: "地理编码",
  geocoded: "地理编码",
  graded: "评分",
  grader: "评分人",
  graph: "图",
  grouping: "分组",
  heading: "标题层级",
  heartbeat: "心跳",
  height: "高度",
  held: "占用",
  highest: "最高",
  history: "历史",
  hmac: "HMAC",
  initial: "初始",
  injection: "注入",
  invalidated: "失效",
  invited: "邀请",
  inviter: "邀请人",
  joined: "加入",
  json: "JSON",
  latency: "延迟",
  latest: "最新",
  latitude: "纬度",
  ledger: "台账",
  lessons: "课时",
  letter: "信件",
  limitation: "限制",
  locales: "语言",
  longitude: "经度",
  marker: "标记",
  matched: "匹配",
  meeting: "会面",
  menu: "菜单",
  meta: "元信息",
  million: "百万",
  moderated: "审核",
  moderation: "审核",
  movement: "变动",
  normalized: "归一化",
  notified: "通知",
  object: "对象",
  observed: "观测",
  offered: "发出",
  opened: "开启",
  original: "原始",
  overridden: "覆盖",
  paid: "支付",
  pair: "配对",
  parse: "解析",
  parsed: "解析",
  parser: "解析器",
  parsing: "解析",
  passed: "通过",
  percent: "百分比",
  performed: "执行",
  placed: "下单",
  previous: "上一",
  principal: "主体",
  progress: "进度",
  promoted: "提升",
  proposed: "提议",
  purchased: "购买",
  random: "随机",
  randomize: "随机",
  rank: "排名",
  raw: "原始",
  received: "接收",
  recording: "录制",
  refunded: "退款",
  refusal: "拒答",
  registry: "注册表",
  rejection: "拒绝",
  released: "释放",
  removal: "移除",
  replaced: "替换",
  replaces: "替换",
  reserved: "预留",
  responded: "回应",
  retention: "留存",
  retired: "下线",
  reviewer: "审核人",
  revocation: "撤销",
  revoke: "撤销",
  rolled: "回滚",
  rotated: "轮换",
  round: "轮次",
  routing: "路由",
  rubric: "评分细则",
  scaled: "缩放",
  scan: "扫描",
  scores: "得分",
  second: "（秒）",
  secret: "密钥",
  section: "章节",
  seek: "拖动",
  serious: "严重",
  sold: "已售",
  speed: "倍速",
  storage: "存储",
  structured: "结构化",
  submitted: "提交",
  summarized: "总结",
  superseded: "被取代",
  suspected: "疑似",
  sync: "同步",
  synced: "同步",
  templates: "模板",
  thread: "会话线程",
  threshold: "阈值",
  timeout: "超时",
  transcription: "转写",
  turns: "轮次",
  unbind: "解绑",
  unbound: "解绑",
  unfollowed: "取关",
  unpublished: "未发布",
  uploaded: "上传",
  validation: "校验",
  virus: "病毒",
  void: "作废",
  voided: "作废",
  waitlisted: "候补",
  width: "宽度",
  withdrawn: "撤回",
};

const exactValues: Record<string, string> = {
  "zh-CN": "简体中文",
  "zh-TW": "繁体中文",
  en: "英文",
  "en-US": "英文（美国）",
  active: "启用",
  inactive: "停用",
  enabled: "启用",
  disabled: "停用",
  pending: "待处理",
  pending_review: "待运营审核",
  deletion_pending: "等待注销",
  time_proposed: "已提出新时间",
  approved_pending_payment: "已批准，等待支付",
  confirmed: "已确认",
  reschedule_requested: "等待确认改期",
  manual_review: "需要人工复核",
  no_show: "未到场",
  in_review: "审核中",
  approval_required: "待审批",
  changes_required: "需要修改",
  draft: "草稿",
  published: "已发布",
  approved: "已批准",
  rejected: "已拒绝",
  completed: "已完成",
  processed: "已处理",
  processing: "处理中",
  queued: "排队中",
  scheduled: "已计划",
  delivered: "已送达",
  sent: "已发送",
  bounced: "已退回",
  suppressed: "已抑制",
  paused: "已暂停",
  cancelled: "已取消",
  canceled: "已取消",
  expired: "已过期",
  resolved: "已解决",
  invalidated: "已失效",
  quarantined: "已隔离",
  registration_open: "报名开放",
  registration_closed: "报名关闭",
  failed: "失败",
  archived: "已归档",
  public: "公开",
  private: "私密",
  internal: "内部可见",
  missing: "缺失",
  verified: "已验证",
  recorded: "已记录",
  open: "待处理",
  closed: "已关闭",
  success: "成功",
  warning: "警告",
  blocked: "已阻断",
  ready: "就绪",
  course: "课程",
  course_bundle: "课程组合",
  activity_ticket: "活动票务",
  counseling_session: "咨询服务",
  counseling_schedule: "辅导排班",
  counseling_followup: "辅导跟进",
  counseling_package: "咨询套餐",
  ai_credit_package: "AI 次数包",
  ai_subscription: "AI 订阅",
  membership: "会员权益",
  digital_service: "数字服务",
  digital_access: "数字访问",
  event_admission: "活动准入",
  appointment_credits: "预约次数",
  ai_credits: "AI 次数",
  membership_entitlement: "会员权益",
  automatic: "自动",
  manual: "手动",
  percentage: "百分比折扣",
  fixed_amount: "固定金额",
  once: "一次性",
  recurring: "周期计费",
  email: "邮件",
  sms: "短信",
  push: "应用推送",
  in_app: "站内通知",
  low: "低",
  medium: "中",
  high: "高",
  critical: "严重",
  info: "信息",
  system: "系统",
  administrator: "管理员",
  content_entry: "内容条目",
  content_media: "媒体内容",
  auth_login_succeeded: "用户登录成功",
  auth_login_failed: "用户登录失败",
  "auth.login.succeeded": "用户登录成功",
  "auth.login.failed": "用户登录失败",
  "auth.registration.created": "用户注册完成",
  "auth.email_verification.sent": "验证邮件已发送",
  "auth.email_verification.completed": "邮箱验证完成",
  "auth.email_verification.bypassed": "邮箱验证被绕过",
  "auth.account.locked": "账户已锁定",
  "auth.refresh_token.reuse_detected": "检测到刷新令牌重复使用",
  "auth.admin_access.removed": "管理员访问权限已移除",
  "auth.session.refreshed": "会话已刷新",
  "auth.session.revoked": "会话已撤销",
  "auth.session.family_revoked": "会话系列已撤销",
  "auth.password.reset.requested": "已申请重置密码",
  "auth.password.reset.completed": "密码重置完成",
  "auth.password.changed": "密码已修改",
  "user.account.suspended": "用户账户已停用",
  "user.account.restored": "用户账户已恢复",
  "user.account.updated": "用户资料已更新",
  "user.account.deactivation_requested": "用户账户已申请注销",
  "user.sessions.revoked": "用户全部会话已撤销",
  "rbac.role.assigned": "角色已分配",
  "rbac.role.revoked": "角色已撤销",
  "admin.invitation.created": "管理员邀请已创建",
  "admin.invitation.revoked": "管理员邀请已撤销",
  "admin.invitation.accepted": "管理员邀请已接受",
  "admin.account.disabled": "管理员账户已停用",
  "admin.account.restored": "管理员账户已恢复",
  "content.entry.created": "内容条目已创建",
  "content.entry.updated": "内容条目已更新",
  "content.entry.submit_review": "内容已提交审核",
  "content.entry.archived": "内容条目已归档",
  "content.entry.version_restored": "内容版本已恢复",
  "content.translation.updated": "内容翻译已更新",
  "content.media.updated": "媒体内容已更新",
  "content.media.deleted": "媒体内容已删除",
  "content.navigation.updated": "导航内容已更新",
  "content.site_setting.updated": "网站设置已更新",
  "content.site_setting.rolled_back": "网站设置已回滚",
  "counseling.schedule.created": "辅导排班已创建",
  "counseling.schedule.disabled": "辅导排班已停用",
  "counseling.appointment.time_reproposed": "辅导预约已重新提出时间",
  "counseling.followup.created": "辅导跟进已创建",
  "counseling.followup.status_changed": "辅导跟进状态已变更",
  "contact.submission.created": "联系记录已创建",
  "contact.submission.status_changed": "联系记录状态已变更",
  "contact.submission.assigned": "联系记录已分配",
  "contact.submission.resolved": "联系记录已处理",
  "Administration workflow: submit-review content after editorial review": "管理流程：编辑复核后提交内容审核",
  photo_not_clear: "照片不清晰",
  photo_not_personal: "非本人照片",
  photo_contains_contact_information: "照片包含联系方式",
  photo_contains_third_party_without_basis: "照片无依据包含第三方",
  photo_inappropriate_content: "照片内容不适宜",
  photo_suspected_impersonation: "疑似冒用身份",
  photo_duplicate: "重复照片",
  photo_quality_too_low: "照片质量过低",
  manual_review_required: "需要人工审核",
};

const dateFieldPattern = /(?:_at|_date|_time|_from|_until|At|Date|Time)$/;
const isoDatePattern = /^\d{4}-\d{2}-\d{2}(?:[T\s].*)?$/;

function translateTokens(value: string): string | undefined {
  const tokens = value.toLowerCase().split(/[._\s:-]+/).filter(Boolean);
  if (!tokens.length || !tokens.every((token) => token in tokenLabels)) return undefined;
  return tokens.map((token) => tokenLabels[token]).join("");
}

export function isAdminDateField(field: string): boolean {
  return dateFieldPattern.test(field);
}

export function formatAdminDate(value: unknown): string {
  if (value === null || value === undefined || value === "") return "—";
  const source = String(value);
  const normalized = /^\d{4}-\d{2}-\d{2}$/.test(source) ? `${source}T00:00:00+08:00` : source;
  const date = new Date(normalized);
  if (Number.isNaN(date.getTime())) return source;
  const parts = new Intl.DateTimeFormat("zh-CN", {
    timeZone: ADMIN_TIME_ZONE,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hourCycle: "h23",
  }).formatToParts(date);
  const part = (type: Intl.DateTimeFormatPartTypes) => parts.find((item) => item.type === type)?.value ?? "";
  return `${part("year")}-${part("month")}-${part("day")} ${part("hour")}:${part("minute")}:${part("second")}（${ADMIN_TIME_ZONE_LABEL}）`;
}

/**
 * Verb -> agent noun for the `*_by` suffix.
 *
 * The plain token table cannot serve here: `approved` has to read "已批准" as a
 * status and "批准人" as an actor, and one entry cannot be both.
 */
const actorVerbLabels: Record<string, string> = {
  approved: "批准", assigned: "分配", authored: "撰写", changed: "变更",
  checked: "核对", created: "创建", evaluated: "评估", excluded: "排除",
  frozen: "冻结", graded: "评分", granted: "授予", invited: "邀请",
  locked: "锁定", moderated: "审核", overridden: "覆盖", override: "覆盖",
  performed: "执行", published: "发布", released: "释放", removed: "移除",
  requested: "申请", reviewed: "审核", revoked: "撤销", unbound: "解绑",
  updated: "更新", uploaded: "上传", verified: "验证",
  license_verified: "版权核验",
};

export function localizeAdminLabel(field: string, fallback?: string): string {
  if (fieldLabels[field]) return fieldLabels[field];

  // `x_by` is always an actor column. Handled as a rule rather than as ~30
  // dictionary rows so a newly added `*_by` field cannot reappear as a raw
  // header. Guarded to the suffix: `replaced_by_certificate_id` is not an actor.
  if (field.endsWith("_by")) {
    const stem = field.slice(0, -3);
    const known = actorVerbLabels[stem];
    if (known) return `${known}人`;
    const translated = translateTokens(stem);
    if (translated) return `${translated}人`;
  }

  // `_basis_points` is a unit, not two nouns: token concatenation produced
  // "自动得分依据基点" where the column means "自动评分（基点）".
  if (field.endsWith("_basis_points")) {
    const stem = field.slice(0, -"_basis_points".length);
    const translated = fieldLabels[stem] ?? translateTokens(stem);
    if (translated) return `${translated}（基点）`;
  }

  // `is_x` / `has_x` are booleans, and Chinese states them as a question.
  const booleanPrefix = /^(is|has)_(.+)$/.exec(field);
  if (booleanPrefix) {
    const translated = fieldLabels[booleanPrefix[2]] ?? translateTokens(booleanPrefix[2]);
    if (translated) return `是否${translated}`;
  }

  if (isAdminDateField(field)) {
    const translated = translateTokens(field.replace(/(?:_at|At)$/, ""));
    return `${translated ?? fallback ?? field}时间（${ADMIN_TIME_ZONE_LABEL}）`;
  }
  if (fallback && /[\u3400-\u9fff]/u.test(fallback)) return fallback;
  const translated = translateTokens(field) ?? translateTokens(fallback ?? "");
  return translated ?? `字段（${fallback ?? field}）`;
}

export function localizeAdminValue(value: unknown, field = ""): string {
  if (value === null || value === undefined || value === "") return "—";
  if (typeof value === "boolean") return value ? "是" : "否";
  if (value instanceof Date || isAdminDateField(field) || (typeof value === "string" && isoDatePattern.test(value))) {
    return formatAdminDate(value);
  }
  if (Array.isArray(value)) return value.length ? value.map((item) => localizeAdminValue(item)).join("、") : "—";
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    return entries.length
      ? entries.map(([key, item]) => `${localizeAdminLabel(key)}：${localizeAdminValue(item, key)}`).join("；")
      : "—";
  }
  const source = String(value);
  if (exactValues[source] !== undefined) return exactValues[source];
  if (/(?:status|state|type|kind|visibility|locale|channel|provider|source|severity|decision)$/i.test(field)) {
    return translateTokens(source) ?? source;
  }
  return source;
}

export function formatAdminTableCell(
  _row: Record<string, unknown>,
  column: { property?: string },
  value: unknown,
): string {
  return localizeAdminValue(value, column.property ?? "");
}

export function adminColumnMinWidth(field: string): number {
  if (field === "severity" || field.endsWith("_type")) return 120;
  if (field === "event_type") return 190;
  if (field === "reason" || field.includes("metadata") || field.endsWith("_state")) return 280;
  if (isAdminDateField(field)) return 220;
  if (field === "id" || field.endsWith("_id")) return 220;
  return 160;
}
